# Generated by Django 4.2.16 on 2024-10-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('cancelled', 'Cancelled'), ('disabled', 'Disabled')], max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('fired', 'Fired'), ('revenue', 'Revenue Manager'), ('flight', 'Flight Manager'), ('board', 'Board Manager'), ('unassigned', 'Unassigned')], max_length=20),
        ),
    ]
