# Generated by Django 5.1.3 on 2024-11-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_airport_is_deleted_board_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardseat',
            name='seats_version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
