# Generated by Django 5.1.3 on 2024-11-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_boardseat_seats_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='delay_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='terminal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
