# Generated by Django 5.1.3 on 2024-11-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_flight_delay_time_flight_gate_flight_terminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_place',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_place',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='api.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='api.airport'),
            preserve_default=False,
        ),
    ]
