# Generated by Django 5.1.3 on 2024-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_flight_arrival_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
