# Generated by Django 5.1.3 on 2024-11-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ticket_is_canceled_ticket_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Аэропорт', 'verbose_name_plural': 'Аэропорты'},
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Борт', 'verbose_name_plural': 'Борты'},
        ),
        migrations.AlterModelOptions(
            name='boardseat',
            options={'verbose_name': 'Место на борту', 'verbose_name_plural': 'Места на борту'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='flightseat',
            options={'verbose_name': 'Место на рейсе', 'verbose_name_plural': 'Места на рейсах'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
