# Generated by Django 5.1.3 on 2024-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_flight_business_class_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseat',
            name='row_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
