# Generated by Django 5.1.3 on 2024-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_flightseat_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
