# Generated by Django 5.1.3 on 2024-11-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_airport_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manufacturer'),
        ),
    ]
