# Generated by Django 5.1.3 on 2024-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
