# Generated by Django 5.1.3 on 2024-12-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_flight_name_user_accent_color_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_number',
            field=models.CharField(max_length=50, verbose_name='Номер борта'),
        ),
        migrations.AlterField(
            model_name='board',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='board',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='board',
            name='seats_amount',
            field=models.IntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='board',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='boardseat',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.board', verbose_name='Борт'),
        ),
        migrations.AlterField(
            model_name='boardseat',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='boardseat',
            name='row_number',
            field=models.IntegerField(verbose_name='Номер ряда'),
        ),
        migrations.AlterField(
            model_name='boardseat',
            name='seat_number',
            field=models.IntegerField(verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='boardseat',
            name='seat_type',
            field=models.CharField(max_length=20, verbose_name='Тип места'),
        ),
        migrations.AlterField(
            model_name='boardseat',
            name='seats_version',
            field=models.IntegerField(verbose_name='Версия мест'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='api.airport', verbose_name='Аэропорт прибытия'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Время прилета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.board', verbose_name='Борт'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='business_class_price',
            field=models.FloatField(default=0.0, verbose_name='Цена бизнес класса'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='delay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время задержки'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='api.airport', verbose_name='Аэропорт отправления'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время вылета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='economy_class_price',
            field=models.FloatField(default=0.0, verbose_name='Цена эконом класса'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='terminal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Терминал'),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight', verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='row_number',
            field=models.IntegerField(verbose_name='Номер ряда'),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='seat',
            field=models.IntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('cancelled', 'Cancelled'), ('disabled', 'Disabled')], max_length=9, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название производителя'),
        ),
        migrations.AlterField(
            model_name='model',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='model',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flightseat', verbose_name='Место на рейсе'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменен'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accent_color',
            field=models.CharField(default='#7d0e85', max_length=7, verbose_name='Цвет акцента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_dark_theme',
            field=models.BooleanField(default=False, verbose_name='Темная тема'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_transparent',
            field=models.BooleanField(default=False, verbose_name='Прозрачный интерфейс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=12, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('fired', 'Fired'), ('revenue', 'Revenue Manager'), ('flight', 'Flight Manager'), ('board', 'Board Manager'), ('unassigned', 'Unassigned')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_user_permissions', to='auth.permission', verbose_name='Права пользователя'),
        ),
    ]
