# Generated by Django 5.1.3 on 2024-12-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_flight_name_alter_airport_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Название'),
        ),
    ]
