# Generated by Django 5.1.3 on 2024-12-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_flight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightseat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
