# Generated by Django 5.1.3 on 2024-12-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_entitylog_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityLog',
        ),
    ]
